CREATE TABLE IF NOT EXISTS CONTENT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    DESC VARCHAR(255) NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    CONTENT_TYPE VARCHAR(255) NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL,
    DATE_MODIFIED TIMESTAMP NOT NULL,
    URL VARCHAR(255) NOT NULL
    );


