CREATE TABLE IF NOT EXISTS CONTENT (
    ID SERIAL PRIMARY KEY ,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    CONTENT_TYPE VARCHAR(255) NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL,
    DATE_UPDATED TIMESTAMP NULL,
    URL VARCHAR(255) NULL
    );

-- INSERT INTO CONTENT (TITLE, `DESC`, STATUS, CONTENT_TYPE, DATE_CREATED)
--     VALUES ('My Spring Data Blog Post', 'A post about spring data', 'IDEA', 'ARTICLE', CURRENT_TIMESTAMP);
