### Get all content
GET http://localhost:8080/api/content


### Create new content
POST http://localhost:8080/api/content
Content-Type:application/json

{
    "id": 2,
    "title": "",
    "desc": "My second blog post",
    "status": "IDEA",
    "contentType": "ARTICLE",
    "dateCreated": "2023-02-27T00:41:10.1278593",
    "dateUpdated": null,
    "url": ""
  }

### Update existing content
PUT http://localhost:8080/api/content/3
Content-Type:application/json

{
    "id": 2,
    "title": "MY SECOND BLOG POST!",
    "desc": "MY SECOND BLOG POST",
    "status": "IDEA",
    "contentType": "ARTICLE",
    "dateCreated": "2023-02-27T00:41:10.1278593",
    "dateUpdated": "2023-02-27T00:41:10.1278593",
    "url": "http://localhost:8080/my-first-blog-post"
  }

### Delete content by id
DELETE http://localhost:8080/api/content/1

### Get content based on keyword from title
GET http://localhost:8080/api/content/filter/GPT

### Get content based on status
GET http://localhost:8080/api/content/filter/status/IDEA
